on:
  push:
  pull_request:
  schedule:
    - cron: "0 7 * * *"

name: Security
jobs:
  Gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          args: ./...
